tools:
  log-path:
    base: C:\Users\User\Desktop\log
    dags1: C:\Users\User\Desktop\log\dags1
    dags2: C:\Users\User\Desktop\log\dags2
    dems1: C:\Users\User\Desktop\log\dems1\trace
    dems2: C:\Users\User\Desktop\log\dems2\trace
    dems1-error: C:\Users\User\Desktop\log\dems1\error\
    dems2-error: C:\Users\User\Desktop\log\dems2\error\